filter:
  excluded_paths: [ tests/* ]

build:
  nodes:
    tests-with-coverage:
      services:
        mysql: 5.7
      environment:
        variables:
          DB_DATABASE: 'test_db'
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
        php:
          version: 8.0
          ini:
            "xdebug.mode": coverage,
            memory_limit: "-1"
      cache:
        directories:
          - tests/.conf/
      tests:
        override:
          - command: mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE IF NOT EXISTS test_db'
          - command: vendor/bin/phpunit --coverage-clover=coverage-file
            coverage:
              file: coverage-file
              format: php-clover
          - php-scrutinizer-run

checks:
  php:
    fix_doc_comments: true
